[package]
name = "sprite-batching"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.33.0"
image = "0.24.7"
winit = "0.28.7"
